resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml

images:
  - name: andydevopstest/frontend
    newTag: 485e8a1afef0a78467c96ad178fa55b2e515fd25
  - name: andydevopstest/backend
    newTag: v1